In [2]:
import numpy as np

In [2]:
arr1=np.array(6)

In [3]:
arr1

array(6)

In [5]:
type(arr1)

numpy.ndarray

In [6]:
range(6)

range(0, 6)

In [7]:
type[arr1]

type[array(6)]

In [8]:
arr2=np.array([1,2,3,4])

In [9]:
arr2

array([1, 2, 3, 4])

In [11]:
arr2=np.array([3,2,5,4])

In [12]:
arr2

array([3, 2, 5, 4])

In [17]:
arr3=np.array([[3,2],[4,5]])

In [18]:
arr3

array([[3, 2],
       [4, 5]])

# Array types



1.zero array
2.ones array
3.empty array
4.array for range

In [21]:
zero_array=np.zeros(2)

In [22]:
zero_array

array([0., 0.])

In [23]:
zero_array=np.zeros((2,2))

In [24]:
zero_array

array([[0., 0.],
       [0., 0.]])

In [25]:
ones_array=np.ones(4)

In [26]:
ones_array

array([1., 1., 1., 1.])

In [28]:
ones_array=np.ones((4,3))

In [29]:
ones_array

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [35]:
arr4=np.arange(6)

In [36]:
arr4

array([0, 1, 2, 3, 4, 5])

In [37]:
np.arange(6)

array([0, 1, 2, 3, 4, 5])

In [38]:
arr4=np.arange(2,18,2)

In [39]:
arr4

array([ 2,  4,  6,  8, 10, 12, 14, 16])

# Transpose

In [42]:
arr5=np.array([[3,2,1],[4,5,3]])

In [43]:
arr5

array([[3, 2, 1],
       [4, 5, 3]])

In [44]:
arr5=np.transpose(arr5)

In [45]:
arr5

array([[3, 4],
       [2, 5],
       [1, 3]])

In [48]:
arr6=np.ravel(arr5)

In [49]:
arr6

array([3, 4, 2, 5, 1, 3])

# Concatenate


In [50]:
a1=np.array([2,3])
a2=np.array([4,5])

In [51]:
a1

array([2, 3])

In [52]:
a2

array([4, 5])

In [53]:
concat=np.concatenate([a1,a2])

In [54]:
concat

array([2, 3, 4, 5])

In [55]:
hori=np.hstack((a1,a2))

In [56]:
hori

array([2, 3, 4, 5])

In [65]:
ver=np.vstack((a1,a2))

In [66]:
ver

array([[2, 3, 4],
       [4, 6, 7]])

In [67]:
a1=np.array([2,
            3,
            4])
a2=np.array([4,
            6,
            7])

In [68]:
hori=np.hstack((a1,a2))

In [69]:
hori

array([2, 3, 4, 4, 6, 7])

In [70]:
ver=np.vstack((a1,a2))

In [71]:
ver

array([[2, 3, 4],
       [4, 6, 7]])

# Determinant

In [19]:
mat1=np.array([[4,2,3],[6,3,1],[0,2,5]])

In [20]:
mat1

array([[4, 2, 3],
       [6, 3, 1],
       [0, 2, 5]])

In [21]:
det_of_mat1=np.linalg.det(mat1)

In [22]:
det_of_mat1

28.00000000000001

# Inverse

In [26]:
inverse=np.linalg.inv(mat1)

In [27]:
inverse

array([[ 0.46428571, -0.14285714, -0.25      ],
       [-1.07142857,  0.71428571,  0.5       ],
       [ 0.42857143, -0.28571429,  0.        ]])

In [28]:
dense=np.array([[0,0,2,3],[1,0,3,0],[0,0,0,5],[0,4,7,0]])

In [29]:
dense

array([[0, 0, 2, 3],
       [1, 0, 3, 0],
       [0, 0, 0, 5],
       [0, 4, 7, 0]])

# Sparse Matrix

In [36]:
from scipy.sparse import csr_matrix

In [37]:
sparse=csr_matrix(dense)

In [38]:
sparse

<4x4 sparse matrix of type '<class 'numpy.intc'>'
	with 7 stored elements in Compressed Sparse Row format>

In [39]:
print(sparse)

  (0, 2)	2
  (0, 3)	3
  (1, 0)	1
  (1, 2)	3
  (2, 3)	5
  (3, 1)	4
  (3, 2)	7
